# Generated by Django 2.2.24 on 2022-10-12 07:25

from django.db import migrations

def add_value_to_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2014).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20221013_0859'),
    ]

    operations = [
        migrations.RunPython(add_value_to_new_building)
    ]
