# Generated by Django 2.2.24 on 2022-10-12 10:08

from django.db import migrations
import phonenumbers

def parse_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_number, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_phone_pure = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumber)
    ]
