# Generated by Django 2.2.24 on 2022-10-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221012_1548'),
        ('property', '0012_auto_20221012_1555'),
    ]

    operations = [
    ]
