# Generated by Django 2.2.24 on 2022-10-12 19:26

from django.db import migrations

def add_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        owner_flats = Flat.objects.filter(owner=owner.name).filter(
            owner_pure_phone=owner.pure_phone)
        owner.flats.set(owner_flats)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_merge_20221012_2202'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owners)
    ]
